INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test@test.com', '테스트유저', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test2@test.com', '테스트유저2', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test3@test.com', '테스트유저3', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test4@test.com', '테스트유저4', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632004,null,0,'yappian',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632021,null,0,'yappian',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632025,null,0,'ruby',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632029,null,0,'nexters',null,0,4);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632030,null,0,'skhu',null,0,4);


INSERT INTO TASK(CREATED_DATE, MODIFIED_DATE, PROJECT_IDX,TITLE, STATUS, JOB, START_DATE, END_DATE, CONTENTS)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'TEST', 0, 3,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '테스트1');

INSERT INTO TASK(CREATED_DATE, MODIFIED_DATE, PROJECT_IDX,TITLE, STATUS, JOB, START_DATE, END_DATE, CONTENTS)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 'TEST2', 1, 2,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '테스트2');

INSERT INTO TASK(CREATED_DATE, MODIFIED_DATE, PROJECT_IDX, TITLE, STATUS, JOB, START_DATE, END_DATE, CONTENTS)
VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 'TEST3', 2, 1,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), '테스트3');


