INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test@test.com', '테스트유저', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632004,null,0,'yappian',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632021,null,0,'yappian',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632025,null,0,'ruby',null,0,5);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632029,null,0,'nexters',null,0,4);

INSERT INTO PROJECT(CREATED_DATE, MODIFIED_DATE,
CREATE_USER_IDX, DESCRIPTION, FINAL_CHECK, NAME, URL, TYPE, ORDERS_IDX)
VALUES (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),
201632030,null,0,'skhu',null,0,4);
