INSERT INTO USER(EMAIL , NAME, USER_ROLE, CREATED_DATE , MODIFIED_DATE)
VALUES ('test@test.com', '테스트유저', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO ORDERS(NUMBER, CREATED_DATE , MODIFIED_DATE)
VALUES (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());